# Generated by Django 3.0.4 on 2020-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_username', models.CharField(max_length=10)),
                ('todo_pass', models.CharField(max_length=6)),
            ],
        ),
    ]
