# Generated by Django 3.0.4 on 2020-05-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_user',
            old_name='todo_pass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='todo_user',
            old_name='todo_username',
            new_name='username',
        ),
    ]
