# Generated by Django 3.0.4 on 2020-05-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200507_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo_user',
            new_name='user',
        ),
    ]
