# Generated by Django 3.0.6 on 2020-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200809_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='creator',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
