# Generated by Django 3.0.6 on 2020-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200818_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='token',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='token',
            field=models.CharField(default=23, max_length=30),
            preserve_default=False,
        ),
    ]
